### ISSUE TITLE
Docs build exceeds the RAM limit on ReadtheDocs

### ISSUE THREAD

**Issue by rw1nkler** [SymbiFlow/symbiflow-docs#195]
The build on ReadtheDocs server exceeds the RAM limit:
https://readthedocs.org/projects/symbiflow/builds/10499598/ 

This is caused by the conda environment and is a well-known issue:
https://github.com/readthedocs/readthedocs.org/issues/6412#issuecomment-560115166

Nevertheless, If we want to use Doxygen on ReadtheDocs we will need conda. Fortunately, In many cases, people from RTD increased the amount of RAM memory for a specific project. Maybe we should ask them for it? 

https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html#requests-more-resources

**Comment by rw1nkler** [comment]
It seems that conda itself uses a lot of RAM memory. Here are results of profiling the conda environment creation process:

1) Conda with all channels:

`environment.yml`:
```
name: SymbiFlow-docs
channels:
  - symbiflow
  - conda-forge
  - defaults
dependencies:
  - doxygen
  - cmake
  - pygobject
  - cairo
  - pango
  - pip
  - pip:
    - -r file:requirements.txt
```

![conda_all_channels](https://user-images.githubusercontent.com/52699314/75545746-6ac8f280-5a27-11ea-8be6-52e0d27686df.png)

2) Conda only with `conda-forge` channel:

`environment.yml`:
```
name: SymbiFlow-docs
channels:
  - conda-forge
dependencies:
  - doxygen
  - cmake
  - pygobject
  - cairo
  - pango
  - pip
  - pip:
    - -r file:requirements.txt
```

![conda_limited_channels](https://user-images.githubusercontent.com/52699314/75546041-09555380-5a28-11ea-8c7d-0e803b366e38.png)

3) Conda only with pip:

`environment.yml`:

```
name: SymbiFlow-docs
channels:
  - symbiflow
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - -r file:requirements.txt
```
`requirements.txt`:
```
Sphinx==2.0.0
```
![conda_only_pip](https://user-images.githubusercontent.com/52699314/75545864-afed2480-5a27-11ea-8713-b4ecd8e95ff0.png)

Profiled using:
```
mprof run --interval 0.01 --include-children ./build/conda/bin/conda env create -q -f environment.yml`
```

**Comment by rw1nkler** [comment]
I've asked the RTD team, and we now have 1.5 Gb of RAM for the building process. 
It seems that this is enough because the build is passing. I will close the issue.

**Comment by mithro** [comment]
@rw1nkler Did you get the memory increased for all the symbiflow related repos?

**Comment by rw1nkler** [comment]
I've asked them only for this repository.
