### ISSUE TITLE
Why is the code link not <>?

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-docs#327]
On page - https://symbiflow.readthedocs.io/en/latest/
![Screenshot from 2020-07-28 18-37-24](https://user-images.githubusercontent.com/21212/88746534-a0baf180-d101-11ea-961f-7a751af3b0d8.png)

The GitHub link should be `<>` like this;
![Screenshot from 2020-07-28 18-39-29](https://user-images.githubusercontent.com/21212/88746573-b3cdc180-d101-11ea-8e7f-f782c7ad88fe.png)

**Comment by daniellimws** [comment]
https://github.com/SymbiFlow/symbiflow-docs/blob/04f3b0293b38004d1f246e3cd11e0f19812503f8/source/conf.py#L139

Should change this line
