### ISSUE TITLE
Documentation should be clear about it's purpose

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-docs#367]
The instructions at https://symbiflow.readthedocs.io/en/latest/symbiflow-arch-defs/docs/source/getting-started.html# are about "getting started to do SymbiFlow toolchain development" rather than "getting started using the SymbiFlow toolchain". This need to be really clear, as a few people have gotten confused.

The "getting started using the SymbiFlow toolchain" is mostly covered by the https://github.com/SymbiFlow/symbiflow-examples repository at the moment.

**Comment by tmichalak** [comment]
Fixed in [PR](https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1726)
